import { Network } from "lucide-react";
import { useState } from "react";

import AgentNode from "./AgentNode";
import type { Agent } from "../../types/agent";
import Card from "../ui/Card";
import StatusDot from "../ui/StatusDot";

const agents: Agent[] = [
  {
    id: "orchestrator",
    name: "Orchestrator",
    role: "Mission planning",
    status: "working",
    tasks: 12,
    description:
      "Coordinates missions and delegates work across the agent network.",
    x: 50,
    y: 50,
  },
  {
    id: "researcher",
    name: "Researcher",
    role: "Information discovery",
    status: "online",
    tasks: 8,
    description:
      "Discovers sources and gathers information required by missions.",
    x: 25,
    y: 28,
  },
  {
    id: "analyst",
    name: "Analyst",
    role: "Reasoning & synthesis",
    status: "working",
    tasks: 5,
    description:
      "Transforms raw information into structured reasoning and conclusions.",
    x: 75,
    y: 28,
  },
  {
    id: "builder",
    name: "Builder",
    role: "Execution",
    status: "online",
    tasks: 9,
    description:
      "Executes implementation tasks generated by the mission.",
    x: 25,
    y: 72,
  },
  {
    id: "validator",
    name: "Validator",
    role: "Quality control",
    status: "waiting",
    tasks: 3,
    description:
      "Validates outputs before they move to the next stage.",
    x: 75,
    y: 72,
  },
];

export default function AgentNetwork() {
  const [selected, setSelected] = useState<Agent>(
    agents[0],
  );

  return (
    <Card className="network-card">
      <div className="section-heading">
        <div>
          <span className="eyebrow">LIVE TOPOLOGY</span>
          <h2>Agent network</h2>
        </div>

        <button
          className="icon-label-button"
          type="button"
        >
          <Network size={15} />
          Explore
        </button>
      </div>

      <div
        className="agent-network"
        aria-label="Interactive AgentGrid agent network"
      >
        <div className="network-grid" />

        <div className="network-glow" />

        <div className="network-line line-one" />
        <div className="network-line line-two" />
        <div className="network-line line-three" />
        <div className="network-line line-four" />

        {agents.map((agent) => (
          <AgentNode
            key={agent.id}
            agent={agent}
            selected={selected.id === agent.id}
            onSelect={setSelected}
          />
        ))}
      </div>

      <div className="selected-agent">
        <div className="selected-agent-info">
          <StatusDot
            status={selected.status}
            label={selected.status}
          />

          <div>
            <strong>{selected.name}</strong>
            <span>
              {selected.description}
            </span>
          </div>
        </div>

        <div className="selected-agent-metric">
          <strong>{selected.tasks}</strong>
          <span>active tasks</span>
        </div>
      </div>
    </Card>
  );
}